assignment/Controllers/StartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using assignment.Models;
namespace assignment.Controllers
{
    public class StartController : Controller
    {
        assignmentdb1Entities db = new assignmentdb1Entities();
        //
        // GET: /Start/
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Insert()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Insert(inserttb tb)
        {
            db.inserttbs.Add(tb);
            db.SaveChanges();
            ViewBag.mess = "inserted success";
            return View();
        }
        public ActionResult ViewRecord()
        {
            return View(db.inserttbs.ToList());
        }
        public ActionResult delete(int[] chkid)
        {
            foreach (int id in chkid)
            {
                var findd = db.inserttbs.Where(x => x.id == id).FirstOrDefault();
                var delete = db.inserttbs.Remove(findd);

            }
            db.SaveChanges();
            return RedirectToAction("ViewRecord");
        }
        public ActionResult select(int id)
        {
            return View(db.inserttbs.Where(x => x.id == id).ToList());
        }
        [HttpPost]
        public ActionResult select(int id, string username, string lastname, string emailaddress, int age)
        {
            var up = db.inserttbs.Where(x => x.id == id).FirstOrDefault();
            up.username = username;
            up.lastname = lastname;
            up.emailaddress = emailaddress;
            up.age = age;
            db.SaveChanges();

            return RedirectToAction("ViewRecord");
        }

	}
}

assignment/Views/Shared/_IndexLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <link href="@Url.Content("~/Content/")vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom fonts for this template-->
    <link href="@Url.Content("~/Content/")vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">

    <!-- Page level plugin CSS-->
    <link href="@Url.Content("~/Content/")vendor/datatables/dataTables.bootstrap4.css" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="@Url.Content("~/Content/")css/sb-admin.css" rel="stylesheet">
</head>
<body id="page-top">
    <nav class="navbar navbar-expand navbar-dark bg-dark static-top">

        <a class="navbar-brand mr-1" href="#">College Assignment</a>

        <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle">
            <i class="fas fa-bars"></i>
        </button>

    </nav>
    <div id="wrapper">
        <!-- Sidebar -->
        <ul class="sidebar navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="@Url.Action("Index","Start")">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>College Assignment</span>
                </a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="pagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-fw fa-folder"></i>
                    <span>Insert</span>
                </a>
                <div class="dropdown-menu" aria-labelledby="pagesDropdown">

                    <a class="dropdown-item" href="@Url.Action("Insert","Start")">Record Insert</a>

                </div>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="pagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-fw fa-folder"></i>
                    <span>View</span>
                </a>
                <div class="dropdown-menu" aria-labelledby="pagesDropdown">

                    <a class="dropdown-item" href="@Url.Action("ViewRecord","Start")">Record View</a>

                </div>
            </li>
        </ul>

        <div id="content-wrapper">
            <div class="container-fluid">
                @RenderBody()

            </div>
        </div>
    </div>
    <!-- Bootstrap core JavaScript-->
    <script src="@Url.Content("~/Content/")vendor/jquery/jquery.min.js"></script>
    <script src="@Url.Content("~/Content/")vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="@Url.Content("~/Content/")vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Page level plugin JavaScript-->
    <script src="@Url.Content("~/Content/")vendor/chart.js/Chart.min.js"></script>
    <script src="@Url.Content("~/Content/")vendor/datatables/jquery.dataTables.js"></script>
    <script src="@Url.Content("~/Content/")vendor/datatables/dataTables.bootstrap4.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="@Url.Content("~/Content/")js/sb-admin.min.js"></script>

    <!-- Demo scripts for this page-->
    <script src="@Url.Content("~/Content/")js/demo/datatables-demo.js"></script>
    <script src="@Url.Content("~/Content/")js/demo/chart-area-demo.js"></script>
</body>
</html>

assignment/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>